<?php

use Illuminate\Database\Migrations\Migration;

class CreateCurrencyTable extends Migration
{
    /**
     * Currencies table name
     *
     * @var string
     */
    protected $table_name;

    /**
     * Create a new migration instance.
     */
    public function __construct()
    {
        $this->table_name = config('currency.drivers.database.table');
    }

    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create($this->table_name, function ($table) {
            $table->increments('id')->unsigned();
            $table->string('name');
            $table->string('code', 10)->index();
            $table->string('symbol', 25);
            $table->string('format', 50);
            $table->string('exchange_rate');
            $table->boolean('active')->default(false);
            $table->timestamps();
        });

        $this->insertData();
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop($this->table_name);
    }

    /**
     * Insert currency data.
     *
     * Formatting data from:
     * http://www.thefinancials.com/Default.aspx?SubSectionID=curformat
     *
     * @return void
     */
    private function insertData()
    {
        DB::table($this->table_name)->insert([
            [
                'id' => 1,
                'name' => 'UAE Dirham',
                'symbol' => 'دإ‏',
                'code' => 'AED',
                'format' => 'دإ‏ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 2,
                'name' => 'Afghanistan, Afghani',
                'symbol' => '؋',
                'code' => 'AFN',
                'format' => '؋1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 3,
                'name' => 'Albania, Lek',
                'symbol' => 'Lek',
                'code' => 'ALL',
                'format' => '1,0.00Lek',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 4,
                'name' => 'Armenian Dram',
                'symbol' => '&#1423;',
                'code' => 'AMD',
                'format' => '1,0.00 &#1423;',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 5,
                'name' => 'Netherlands Antillian Guilder',
                'symbol' => 'ƒ',
                'code' => 'ANG',
                'format' => 'ƒ1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 6,
                'name' => 'Angola, Kwanza',
                'symbol' => 'Kz',
                'code' => 'AOA',
                'format' => 'Kz1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 7,
                'name' => 'Argentine Peso',
                'symbol' => '$',
                'code' => 'ARS',
                'format' => '$ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 8,
                'name' => 'Australian Dollar',
                'symbol' => '$',
                'code' => 'AUD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 9,
                'name' => 'Aruban Guilder',
                'symbol' => 'ƒ',
                'code' => 'AWG',
                'format' => 'ƒ1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 10,
                'name' => 'Azerbaijanian Manat',
                'symbol' => '₼',
                'code' => 'AZN',
                'format' => '1 0,00 ₼',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 11,
                'name' => 'Bosnia and Herzegovina, Convertible Marks',
                'symbol' => 'КМ',
                'code' => 'BAM',
                'format' => '1,0.00 КМ',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 12,
                'name' => 'Barbados Dollar',
                'symbol' => '$',
                'code' => 'BBD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 13,
                'name' => 'Bangladesh, Taka',
                'symbol' => '৳',
                'code' => 'BDT',
                'format' => '৳ 1,0.',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 14,
                'name' => 'Bulgarian Lev',
                'symbol' => 'лв.',
                'code' => 'BGN',
                'format' => '1 0,00 лв.',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 15,
                'name' => 'Bahraini Dinar',
                'symbol' => '.د.',
                'code' => 'BHD',
                'format' => '.د. 1,0.000',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 16,
                'name' => 'Burundi Franc',
                'symbol' => 'FBu',
                'code' => 'BIF',
                'format' => '1,0.FBu',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 17,
                'name' => 'Bermudian Dollar',
                'symbol' => '$',
                'code' => 'BMD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 18,
                'name' => 'Brunei Dollar',
                'symbol' => '$',
                'code' => 'BND',
                'format' => '$1,0.',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 19,
                'name' => 'Bolivia, Boliviano',
                'symbol' => 'Bs',
                'code' => 'BOB',
                'format' => 'Bs 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 20,
                'name' => 'Brazilian Real',
                'symbol' => 'R$',
                'code' => 'BRL',
                'format' => 'R$ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 21,
                'name' => 'Bahamian Dollar',
                'symbol' => '$',
                'code' => 'BSD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 22,
                'name' => 'Bhutan, Ngultrum',
                'symbol' => 'Nu.',
                'code' => 'BTN',
                'format' => 'Nu. 1,0.0',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 23,
                'name' => 'Botswana, Pula',
                'symbol' => 'P',
                'code' => 'BWP',
                'format' => 'P1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 24,
                'name' => 'Belarussian Ruble',
                'symbol' => 'р.',
                'code' => 'BYR',
                'format' => '1 0,00 р.',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 25,
                'name' => 'Belize Dollar',
                'symbol' => 'BZ$',
                'code' => 'BZD',
                'format' => 'BZ$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 26,
                'name' => 'Canadian Dollar',
                'symbol' => '$',
                'code' => 'CAD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 27,
                'name' => 'Franc Congolais',
                'symbol' => 'FC',
                'code' => 'CDF',
                'format' => '1,0.00FC',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 28,
                'name' => 'Swiss Franc',
                'symbol' => 'CHF',
                'code' => 'CHF',
                'format' => '1\'0.00 CHF',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 29,
                'name' => 'Chilean Peso',
                'symbol' => '$',
                'code' => 'CLP',
                'format' => '$ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 30,
                'name' => 'China Yuan Renminbi',
                'symbol' => '¥',
                'code' => 'CNY',
                'format' => '¥1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 31,
                'name' => 'Colombian Peso',
                'symbol' => '$',
                'code' => 'COP',
                'format' => '$ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 32,
                'name' => 'Costa Rican Colon',
                'symbol' => '₡',
                'code' => 'CRC',
                'format' => '₡1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 33,
                'name' => 'Cuban Convertible Peso',
                'symbol' => 'CUC',
                'code' => 'CUC',
                'format' => 'CUC1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 34,
                'name' => 'Cuban Peso',
                'symbol' => '$MN',
                'code' => 'CUP',
                'format' => '$MN1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 35,
                'name' => 'Cape Verde Escudo',
                'symbol' => '$',
                'code' => 'CVE',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 36,
                'name' => 'Czech Koruna',
                'symbol' => 'Kč',
                'code' => 'CZK',
                'format' => '1 0,00 Kč',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 37,
                'name' => 'Djibouti Franc',
                'symbol' => 'Fdj',
                'code' => 'DJF',
                'format' => '1,0.Fdj',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 38,
                'name' => 'Danish Krone',
                'symbol' => 'kr.',
                'code' => 'DKK',
                'format' => 'kr. 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 39,
                'name' => 'Dominican Peso',
                'symbol' => 'RD$',
                'code' => 'DOP',
                'format' => 'RD$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 40,
                'name' => 'Algerian Dinar',
                'symbol' => 'د.ج‏',
                'code' => 'DZD',
                'format' => 'د.ج‏ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 41,
                'name' => 'Egyptian Pound',
                'symbol' => 'ج.م',
                'code' => 'EGP',
                'format' => 'ج.م 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 42,
                'name' => 'Eritrea, Nakfa',
                'symbol' => 'Nfk',
                'code' => 'ERN',
                'format' => '1,0.00Nfk',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 43,
                'name' => 'Ethiopian Birr',
                'symbol' => 'ETB',
                'code' => 'ETB',
                'format' => 'ETB1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 44,
                'name' => 'Euro',
                'symbol' => '€',
                'code' => 'EUR',
                'format' => '1 0,00 €',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 45,
                'name' => 'Fiji Dollar',
                'symbol' => '$',
                'code' => 'FJD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 46,
                'name' => 'Falkland Islands Pound',
                'symbol' => '£',
                'code' => 'FKP',
                'format' => '£1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 47,
                'name' => 'Pound Sterling',
                'symbol' => '£',
                'code' => 'GBP',
                'format' => '£1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 48,
                'name' => 'Georgia, Lari',
                'symbol' => 'Lari',
                'code' => 'GEL',
                'format' => '1 0,00 Lari',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 49,
                'name' => 'Ghana Cedi',
                'symbol' => '₵',
                'code' => 'GHS',
                'format' => '₵1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 50,
                'name' => 'Gibraltar Pound',
                'symbol' => '£',
                'code' => 'GIP',
                'format' => '£1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 51,
                'name' => 'Gambia, Dalasi',
                'symbol' => 'D',
                'code' => 'GMD',
                'format' => '1,0.00D',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 52,
                'name' => 'Guatemala, Quetzal',
                'symbol' => 'Q',
                'code' => 'GTQ',
                'format' => 'Q1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 53,
                'name' => 'Guyana Dollar',
                'symbol' => '$',
                'code' => 'GYD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 54,
                'name' => 'Hong Kong Dollar',
                'symbol' => 'HK$',
                'code' => 'HKD',
                'format' => 'HK$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 55,
                'name' => 'Honduras, Lempira',
                'symbol' => 'L.',
                'code' => 'HNL',
                'format' => 'L. 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 56,
                'name' => 'Croatian Kuna',
                'symbol' => 'kn',
                'code' => 'HRK',
                'format' => '1,0.00 kn',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 57,
                'name' => 'Haiti, Gourde',
                'symbol' => 'G',
                'code' => 'HTG',
                'format' => 'G1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 58,
                'name' => 'Hungary, Forint',
                'symbol' => 'Ft',
                'code' => 'HUF',
                'format' => '1 0,00 Ft',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 59,
                'name' => 'Indonesia, Rupiah',
                'symbol' => 'Rp',
                'code' => 'IDR',
                'format' => 'Rp1,0.',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 60,
                'name' => 'New Israeli Shekel',
                'symbol' => '₪',
                'code' => 'ILS',
                'format' => '₪ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 61,
                'name' => 'Indian Rupee',
                'symbol' => '₹',
                'code' => 'INR',
                'format' => '1,0.00₹',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 62,
                'name' => 'Iraqi Dinar',
                'symbol' => 'د.ع.‏',
                'code' => 'IQD',
                'format' => 'د.ع.‏ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 63,
                'name' => 'Iranian Rial',
                'symbol' => '﷼',
                'code' => 'IRR',
                'format' => '﷼ 1,0/00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 64,
                'name' => 'Iceland Krona',
                'symbol' => 'kr.',
                'code' => 'ISK',
                'format' => '1,0. kr.',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 65,
                'name' => 'Jamaican Dollar',
                'symbol' => 'J$',
                'code' => 'JMD',
                'format' => 'J$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 66,
                'name' => 'Jordanian Dinar',
                'symbol' => 'د.ا.‏',
                'code' => 'JOD',
                'format' => 'د.ا.‏ 1,0.000',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 67,
                'name' => 'Japan, Yen',
                'symbol' => '¥',
                'code' => 'JPY',
                'format' => '¥1,0.',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 68,
                'name' => 'Kenyan Shilling',
                'symbol' => 'S',
                'code' => 'KES',
                'format' => 'S1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 69,
                'name' => 'Kyrgyzstan, Som',
                'symbol' => 'сом',
                'code' => 'KGS',
                'format' => '1 0-00 сом',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 70,
                'name' => 'Cambodia, Riel',
                'symbol' => '៛',
                'code' => 'KHR',
                'format' => '1,0.៛',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 71,
                'name' => 'Comoro Franc',
                'symbol' => 'CF',
                'code' => 'KMF',
                'format' => '1,0.00CF',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 72,
                'name' => 'North Korean Won',
                'symbol' => '₩',
                'code' => 'KPW',
                'format' => '₩1,0.',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 73,
                'name' => 'South Korea, Won',
                'symbol' => '₩',
                'code' => 'KRW',
                'format' => '₩1,0.',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 74,
                'name' => 'Kuwaiti Dinar',
                'symbol' => 'دينار‎‎‏',
                'code' => 'KWD',
                'format' => 'دينار‎‎‏ 1,0.000',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 75,
                'name' => 'Cayman Islands Dollar',
                'symbol' => '$',
                'code' => 'KYD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 76,
                'name' => 'Kazakhstan, Tenge',
                'symbol' => '₸',
                'code' => 'KZT',
                'format' => '₸1 0-00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 77,
                'name' => 'Laos, Kip',
                'symbol' => '₭',
                'code' => 'LAK',
                'format' => '1,0.₭',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 78,
                'name' => 'Lebanese Pound',
                'symbol' => 'ل.ل.‏',
                'code' => 'LBP',
                'format' => 'ل.ل.‏ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 79,
                'name' => 'Sri Lanka Rupee',
                'symbol' => '₨',
                'code' => 'LKR',
                'format' => '₨ 1,0.',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 80,
                'name' => 'Liberian Dollar',
                'symbol' => '$',
                'code' => 'LRD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 81,
                'name' => 'Lesotho, Loti',
                'symbol' => 'M',
                'code' => 'LSL',
                'format' => '1,0.00M',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 82,
                'name' => 'Libyan Dinar',
                'symbol' => 'د.ل.‏',
                'code' => 'LYD',
                'format' => 'د.ل.‏1,0.000',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 83,
                'name' => 'Moroccan Dirham',
                'symbol' => 'د.م.‏',
                'code' => 'MAD',
                'format' => 'د.م.‏ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 84,
                'name' => 'Moldovan Leu',
                'symbol' => 'lei',
                'code' => 'MDL',
                'format' => '1,0.00 lei',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 85,
                'name' => 'Malagasy Ariary',
                'symbol' => 'Ar',
                'code' => 'MGA',
                'format' => 'Ar1,0.',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 86,
                'name' => 'Macedonia, Denar',
                'symbol' => 'ден.',
                'code' => 'MKD',
                'format' => '1,0.00 ден.',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 87,
                'name' => 'Myanmar, Kyat',
                'symbol' => 'K',
                'code' => 'MMK',
                'format' => 'K1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 88,
                'name' => 'Mongolia, Tugrik',
                'symbol' => '₮',
                'code' => 'MNT',
                'format' => '₮1 0,00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 89,
                'name' => 'Macao, Pataca',
                'symbol' => 'MOP$',
                'code' => 'MOP',
                'format' => 'MOP$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 90,
                'name' => 'Mauritania, Ouguiya',
                'symbol' => 'UM',
                'code' => 'MRO',
                'format' => '1,0.00UM',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 91,
                'name' => 'Maltese Lira',
                'symbol' => '₤',
                'code' => 'MTL',
                'format' => '₤1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 92,
                'name' => 'Mauritius Rupee',
                'symbol' => '₨',
                'code' => 'MUR',
                'format' => '₨1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 93,
                'name' => 'Maldives, Rufiyaa',
                'symbol' => 'MVR',
                'code' => 'MVR',
                'format' => '1,0.0 MVR',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 94,
                'name' => 'Malawi, Kwacha',
                'symbol' => 'MK',
                'code' => 'MWK',
                'format' => 'MK1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 95,
                'name' => 'Mexican Peso',
                'symbol' => '$',
                'code' => 'MXN',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 96,
                'name' => 'Malaysian Ringgit',
                'symbol' => 'RM',
                'code' => 'MYR',
                'format' => 'RM1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 97,
                'name' => 'Mozambique Metical',
                'symbol' => 'MT',
                'code' => 'MZN',
                'format' => 'MT1,0.',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 98,
                'name' => 'Namibian Dollar',
                'symbol' => '$',
                'code' => 'NAD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 99,
                'name' => 'Nigeria, Naira',
                'symbol' => '₦',
                'code' => 'NGN',
                'format' => '₦1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 100,
                'name' => 'Nicaragua, Cordoba Oro',
                'symbol' => 'C$',
                'code' => 'NIO',
                'format' => 'C$ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 101,
                'name' => 'Norwegian Krone',
                'symbol' => 'kr',
                'code' => 'NOK',
                'format' => 'kr 1 0,00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 102,
                'name' => 'Nepalese Rupee',
                'symbol' => '₨',
                'code' => 'NPR',
                'format' => '₨1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 103,
                'name' => 'New Zealand Dollar',
                'symbol' => '$',
                'code' => 'NZD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 104,
                'name' => 'Rial Omani',
                'symbol' => '﷼',
                'code' => 'OMR',
                'format' => '﷼ 1,0.000',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 105,
                'name' => 'Panama, Balboa',
                'symbol' => 'B/.',
                'code' => 'PAB',
                'format' => 'B/. 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 106,
                'name' => 'Peru, Nuevo Sol',
                'symbol' => 'S/.',
                'code' => 'PEN',
                'format' => 'S/. 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 107,
                'name' => 'Papua New Guinea, Kina',
                'symbol' => 'K',
                'code' => 'PGK',
                'format' => 'K1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 108,
                'name' => 'Philippine Peso',
                'symbol' => '₱',
                'code' => 'PHP',
                'format' => '₱1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 109,
                'name' => 'Pakistan Rupee',
                'symbol' => '₨',
                'code' => 'PKR',
                'format' => '₨1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 110,
                'name' => 'Poland, Zloty',
                'symbol' => 'zł',
                'code' => 'PLN',
                'format' => '1 0,00 zł',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 111,
                'name' => 'Paraguay, Guarani',
                'symbol' => '₲',
                'code' => 'PYG',
                'format' => '₲ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 112,
                'name' => 'Qatari Rial',
                'symbol' => '﷼',
                'code' => 'QAR',
                'format' => '﷼ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 113,
                'name' => 'Romania, New Leu',
                'symbol' => 'lei',
                'code' => 'RON',
                'format' => '1,0.00 lei',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 114,
                'name' => 'Serbian Dinar',
                'symbol' => 'Дин.',
                'code' => 'RSD',
                'format' => '1,0.00 Дин.',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 115,
                'name' => 'Russian Ruble',
                'symbol' => '₽',
                'code' => 'RUB',
                'format' => '1 0,00 ₽',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 116,
                'name' => 'Rwanda Franc',
                'symbol' => 'RWF',
                'code' => 'RWF',
                'format' => 'RWF 1 0,00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 117,
                'name' => 'Saudi Riyal',
                'symbol' => '﷼',
                'code' => 'SAR',
                'format' => '﷼ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 118,
                'name' => 'Solomon Islands Dollar',
                'symbol' => '$',
                'code' => 'SBD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 119,
                'name' => 'Seychelles Rupee',
                'symbol' => '₨',
                'code' => 'SCR',
                'format' => '₨1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 120,
                'name' => 'Sudanese Dinar',
                'symbol' => 'LSd',
                'code' => 'SDD',
                'format' => '1,0.00LSd',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 121,
                'name' => 'Swedish Krona',
                'symbol' => 'kr',
                'code' => 'SEK',
                'format' => '1,0.00 kr',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 122,
                'name' => 'Singapore Dollar',
                'symbol' => '$',
                'code' => 'SGD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 123,
                'name' => 'Saint Helena Pound',
                'symbol' => '£',
                'code' => 'SHP',
                'format' => '£1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 124,
                'name' => 'Sierra Leone, Leone',
                'symbol' => 'Le',
                'code' => 'SLL',
                'format' => 'Le1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 125,
                'name' => 'Somali Shilling',
                'symbol' => 'S',
                'code' => 'SOS',
                'format' => 'S1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 126,
                'name' => 'Surinam Dollar',
                'symbol' => '$',
                'code' => 'SRD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 127,
                'name' => 'Sao Tome and Principe, Dobra',
                'symbol' => 'Db',
                'code' => 'STD',
                'format' => 'Db1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 128,
                'name' => 'El Salvador Colon',
                'symbol' => '₡',
                'code' => 'SVC',
                'format' => '₡1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 129,
                'name' => 'Syrian Pound',
                'symbol' => '£',
                'code' => 'SYP',
                'format' => '£ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 130,
                'name' => 'Swaziland, Lilangeni',
                'symbol' => 'E',
                'code' => 'SZL',
                'format' => 'E1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 131,
                'name' => 'Thailand, Baht',
                'symbol' => '฿',
                'code' => 'THB',
                'format' => '฿1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 132,
                'name' => 'Tajikistan, Somoni',
                'symbol' => 'TJS',
                'code' => 'TJS',
                'format' => '1 0;00 TJS',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 133,
                'name' => 'Turkmenistani New Manat',
                'symbol' => 'm',
                'code' => 'TMT',
                'format' => '1 0,m',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 134,
                'name' => 'Tunisian Dinar',
                'symbol' => 'د.ت.‏',
                'code' => 'TND',
                'format' => 'د.ت.‏ 1,0.000',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 135,
                'name' => 'Tonga, Paanga',
                'symbol' => 'T$',
                'code' => 'TOP',
                'format' => 'T$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 136,
                'name' => 'New Turkish Lira',
                'symbol' => 'TL',
                'code' => 'TRY',
                'format' => '1,0.00 TL',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 137,
                'name' => 'Trinidad and Tobago Dollar',
                'symbol' => 'TT$',
                'code' => 'TTD',
                'format' => 'TT$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 138,
                'name' => 'New Taiwan Dollar',
                'symbol' => 'NT$',
                'code' => 'TWD',
                'format' => 'NT$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 139,
                'name' => 'Tanzanian Shilling',
                'symbol' => 'TSh',
                'code' => 'TZS',
                'format' => 'TSh1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 140,
                'name' => 'Ukraine, Hryvnia',
                'symbol' => '₴',
                'code' => 'UAH',
                'format' => '1 0,00₴',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 141,
                'name' => 'Uganda Shilling',
                'symbol' => 'USh',
                'code' => 'UGX',
                'format' => 'USh1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 142,
                'name' => 'US Dollar',
                'symbol' => '$',
                'code' => 'USD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 143,
                'name' => 'Peso Uruguayo',
                'symbol' => '$U',
                'code' => 'UYU',
                'format' => '$U 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 144,
                'name' => 'Uzbekistan Sum',
                'symbol' => 'сўм',
                'code' => 'UZS',
                'format' => '1 0,00 сўм',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 145,
                'name' => 'Venezuela Bolivares Fuertes',
                'symbol' => 'Bs. F.',
                'code' => 'VEF',
                'format' => 'Bs. F. 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 146,
                'name' => 'Viet Nam, Dong',
                'symbol' => '₫',
                'code' => 'VND',
                'format' => '1,0.0 ₫',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 147,
                'name' => 'Vanuatu, Vatu',
                'symbol' => 'VT',
                'code' => 'VUV',
                'format' => '1,0.VT',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 148,
                'name' => 'Samoa, Tala',
                'symbol' => 'WS$',
                'code' => 'WST',
                'format' => 'WS$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 149,
                'name' => 'Franc de la Communaute financi',
                'symbol' => 'F',
                'code' => 'XAF',
                'format' => '1,0.00F',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 150,
                'name' => 'East Caribbean Dollar',
                'symbol' => '$',
                'code' => 'XCD',
                'format' => '$1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 151,
                'name' => 'CFP Franc',
                'symbol' => 'F',
                'code' => 'XPF',
                'format' => '1,0.00F',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 152,
                'name' => 'Yemeni Rial',
                'symbol' => '﷼',
                'code' => 'YER',
                'format' => '﷼ 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 153,
                'name' => 'South Africa, Rand',
                'symbol' => 'R',
                'code' => 'ZAR',
                'format' => 'R 1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
            [
                'id' => 154,
                'name' => 'Zambia Kwacha',
                'symbol' => 'ZK',
                'code' => 'ZMW',
                'format' => 'ZK1,0.00',
                'exchange_rate' => 0.00,
                'active' => 0,
                'created_at' => '2015-07-22 23:25:30',
                'updated_at' => '2015-07-22 23:25:30',
            ],
        ]);
    }
}
